### PR TITLE
Add idx to codeaction selector

### PR DESCRIPTION
**Pull request by qRoC**
Add idx to codeaction selector

This allows you to quickly select an action from a list.

Current:

Screenshot 2022-09-15 at 12 56 55

This PR:

Screenshot 2022-09-15 at 12 55 25
Screenshot 2022-09-15 at 12 55 30

### CODE REVIEW

**Comment by qRoC** [comment]
needs remove plenary dependency?

**Comment by stevearc** [comment]
Looks good! But yes, please remove the plenary dependency. `vim.api.nvim_strwidth` should function the same.

**Comment by qRoC** [comment]
@stevearc done

**Comment by stevearc** [comment]
Awesome, thanks!

**Pull request merged**
